"""
For some unknown reason, there are sometimes duplicated lines in the csv files generated by the roost-system.
This script cleans the duplications.
"""

import os

DIR = "/scratch2/wenlongzhao/roostui/data/all_stations_v2"

for file in os.listdir(DIR):
    if file.startswith("scans") or file.startswith("tracks"):
        lines = open(os.path.join(DIR, file), "r").readlines()
        good_lines = []
        good_lines_set = set()

        for line in lines:
            if line not in good_lines_set:
                good_lines.append(line)
                good_lines_set.add(line)

        with open(os.path.join(DIR, file), "w") as f:
            f.writelines(good_lines)
